services:
  app:
    build: .
    container_name: jobsearcher-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLITE_DB_PATH=/data/telegram_messages.db
      - SESSION_NAME=/sessions/jobsearcher
    volumes:
      - ./data:/data
      - ./sessions:/sessions
    tty: true
    stdin_open: true

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: jobsearcher-sqlite-web
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - SQLITE_DATABASE=/data/telegram_messages.db
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data

  n8n:
    image: n8nio/n8n:latest
    container_name: jobsearcher-n8n
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Europe/Moscow
      - TZ=Europe/Moscow
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/data:ro

volumes:
  n8n_data: {}
