services:
  app:
    build: .
    container_name: jobsearcher-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLITE_DB_PATH=/data/telegram_messages.db
      # SESSION_NAME больше не нужен при TELEGRAM_STRING_SESSION
    volumes:
      - ./data:/data
    # никаких tty/stdin_open

  processor:
    build: .
    container_name: jobsearcher-processor
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SQLITE_DB_PATH=/data/telegram_messages.db
    depends_on:
      - app
    volumes:
      - ./data:/data
    command: ["python", "processor.py"]

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: jobsearcher-sqlite-web
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - SQLITE_DATABASE=/data/telegram_messages.db
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
